global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-chatwoot'
    static_configs:
      - targets: ['postgres-exporter-chatwoot:9187']

  - job_name: 'postgres-evolution'
    static_configs:
      - targets: ['postgres-exporter-evolution:9188']

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']

  - job_name: 'chatwoot-rails'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:9394']

  - job_name: 'evolution-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:9394']
